name: CI

on:
  pull_request:
    branches:
    - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        version: 12
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: npm install
    - name: Lint code
      run: npm run lint
    - name: Build distribution
      run: npm run build
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        version: 12
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: npm install
    - name: Run tests
      run: npm run test



